# Site settings
author: Will Cao
title: Software Engineering
header-img: img/home-bg.png
email: williamacao@gmail.com
copyright_name: Will Cao
description: > # this means to ignore newlines until "baseurl:"
  Learning one code at a time
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  laughingcao

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
